version: "3.8"
services:
  openvoice-api:
    image: openvoice-api-python
    container_name: openvoice
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - "SPEAKERS=cerbinou"
      - "MODEL_LANGUAGES_V2=FR"
      - "MODEL_LANGUAGES_V1="
      - "DEFAULT_LANGUAGE=FR"
      - "LOG_LEVEL=INFO"
    ports:
      - "8381:5000/tcp"
    command:
      - python3 
      - app.py
    volumes:
      - /mnt/e/workspace/my-scripts/cerbinou/tts/speakers:/app/speakers:rw
      - /mnt/e/workspace/my-scripts/cerbinou/tts/processed:/app/processed:rw
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:v1.6.0-gpu
    container_name: whisper
    restart: unless-stopped
    environment:
      - "ASR_MODEL=/root/models/bofenghuang/whisper-large-v3-distil-fr-v0.2/ctranslate2"
      - "ASR_ENGINE=faster_whisper" #openai_whisper,faster_whisper
    ports:
      - "9000:9000/tcp"  
    volumes:
      - /mnt/g/Utils/whisper/cache:/root/.cache/whisper:rw
      - /mnt/g/Utils/whisper/models:/root/models:rw
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]